language: php
php:
  - 7.3

env:
  - COMMAND="install"
  - COMMAND="update"

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer ${COMMAND}
  - if [[ "$TRAVIS_PHP_VERSION" == "7.3" ]]; then composer require --dev vimeo/psalm; fi

script:
  - bin/check-syntax.sh
  - if [[ "$TRAVIS_PHP_VERSION" == "7.3" ]]; then vendor/bin/psalm; fi
